### ISSUE TITLE
No preview of questions showing for Exercise Editor

### ISSUE THREAD

**Issue by jayoshih** [learningequality/sushibar#155]
## Summary
The Preview tab for the exercise editor doesn't show a preview of the questions inputted for the exercise. 
 Currently, the preview only shows a thumbnail.  I expect a preview of the question-answering experience from a learner view.

## Usage Details
_Please give details in how were you using the Content Curation Server._

* Browser: Chrome
* Channel: BeStrong Module : d0ef6f71e4fe4e54bb87d7dab5eeaae2
* Topic/Content Item: There is one exercise called "Quiz" under each Module
Ex. Module 1: My Digital Life --> Quiz - My Digital Life

## How to reproduce
1. Log into content workshop
1. Start editing the Be Strong channel
1. Edit the exercise under each module
1. Click 'Preview' while editing exercise

## Screenshots
![exercisepreview](https://cloud.githubusercontent.com/assets/5150483/26127889/a71ece36-3a3f-11e7-8c7e-ba21e1aaf36a.png)

## Real-life consequences (anything community should be aware of, for instance how it affects end users)
Suboptimal experience for content creators who are curious to know how their questions will look to the user/learner.

**Comment by rtibbles** [comment]
Why was this issue on sushibar? This is a Studio issue, no?

For Studio, this is in process, I started the work and @DXCanas is finishing it up.

The two main extant things that need fixing are dynamic switching behaviour (that @DXCanas has been working on, but has required a bit of refactor), and dynamic exercise generation (based on either the ricecooker generated perseus JSON, or based on the exercise question database data).

**Comment by ivanistheone** [comment]
@rtibbles Yes, it's a studio issue https://github.com/learningequality/studio/issues/303 

Yesterday there were some issues with a new task/project management software we're testing to organize the content dev projects, so a lot of issues got mixed up between the repos. Sorry for the notification spam, it should all be all fixed now.
